### ISSUE TITLE
emergency accept page

### ISSUE THREAD

**Issue by felixevers** [Just-another-Muensterhack/helpwave-frontend#35]

**Comment by FoseFx** [comment]
google maps api key pls https://developers.google.com/maps/documentation/android-sdk/get-api-key @use-to

**Comment by FoseFx** [comment]
![image](https://user-images.githubusercontent.com/22842759/192039268-916ff759-78f2-43fc-9a2a-aa2998066285.png)

bleeding edge bruder

**Comment by FoseFx** [comment]
nvm ich versuch's mit mapbox
